name: Update Package Lock

on:
  workflow_dispatch:

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Delete old lockfile
        run: rm -f package-lock.json
      
      - name: Install dependencies and generate lockfile
        run: npm install --package-lock-only
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update package-lock.json to match dependencies"
          file_pattern: 'package-lock.json'
